#define ch char
#define in int
#define lo long
#define ui8 uint8_t
#define ui16 uint16_t
#define ui32 uint32_t
#define ui64 uint64_t
#define i8 int8_t
#define i16 int16_t
#define i32 int32_t
#define i64 int64_t
#define str string
#define vec vector
#define lst list
#define deq deque
#define fr for
#define wh while
#define el else
#define au auto
#define sw switch