#define ch char
#define in int
#define lo long
#define u8 uint8_t
#define u16 uint16_t
#define u32 uint32_t
#define u64 uint64_t
#define i8 int8_t
#define i16 int16_t
#define i32 int32_t
#define i64 int64_t
#define str string
#define vec vector
#define lst list
#define deq deque
#define fr for
#define wh while
#define el else
#define au auto
#define sw switch
#define cs case
#define ot cout
#define cst const
